### ISSUE TITLE
:Sayonara! closes a window if the buffer is shown in multiple windows

### ISSUE THREAD

**Issue by mhinz** [mhinz/vim-sayonara#2]

**Comment by fatih** [comment]
Not sure if this is the same. But If I have two tabs open with two windows and the same buffer. If I close the buffer with `:Sayanora`, it closes the other window too. I think it shouldn't do it. Should I open a PR or is it the same with this issue?

**Comment by mhinz** [comment]
Yup, I think it's the same issue. Thanks for reporting!

**Comment by mhinz** [comment]
I had no time to properly test it yet, but it should work in this branch:

`git pull && git checkout preserve-all-windows`

I'll do some more tests tomorrow and merge it into master if I don't find any other issues.

**Comment by mhinz** [comment]
Okay, it should work now. It's merged into master.

**Comment by fatih** [comment]
Ok it works but it's still broken. Let me say how you can introduce it
1. open a.go in the same tab
2. open b.go in the same tab (next to a.go)
3. open a.go in another tab
4. open b.go in another tab (next to a.go)

No close `b.go` in another tab, everything is ok. Now if you close a.go in the another tab too, all buffers are closed.

**Comment by mhinz** [comment]
Hmm, this is kind of expected. What do think should happen? (The plugin is in an early phase, so I can still change its behavior.)

Something I'd like to see, are tab-local buffer lists, but Vim treats all buffers as globally over all tabpages.

So, after your 4 steps, when you do `:Sayonara` or `:Sayonara!`, `b.go` is deleted, so both windows in both tabpages will show `a.go` now instead (the only other listed and previous buffer).

Now both commands act differently:

**:Sayonara!**: `a.go` is deleted and both tabpages will show a scratch buffer

**:Sayonara**: `a.go` is deleted and since there are no other listed buffers to switch to, and there is only a single window per tab, all tabs but one get closed. (This is what you see, I guess.)

(BTW, yesterday I updated the helptags to explain how the commands work in detail: `:h sayonara-details`.)

**Comment by fatih** [comment]
I don't see this. Let's say I have two tabs open, both with `a.go` and `b.go` (as explained in my previous example).
1. Close b.go with `:Sayanora` in second tab. Expected output: First tab: `a.go` and `b.go` both open. Second Tab: `a.go` is open. Result: same, so everything is ok.
2. Close a.go with `:Sayanora` in second tab. Expected output: First tab: `a.go` and `b.go` both open. Second Tab: nothing, completely closed. Result: All buffers are closed, first tab has two empty scratch buffers.

I think that there is an inconsistency here.

**Comment by mhinz** [comment]
> Close b.go with :Sayanora in second tab. Expected output: First tab: a.go and b.go both open. Second Tab: a.go is open. Result: same, so everything is ok.

Now I'm confused. If you use `:Sayonara` in the second tab, `b.go` is _deleted_, so it shouldn't be shown in the first tab anymore as well. (This is what I meant with gobal buffer list; deleting a buffer deletes that buffer in every tab.)

After doing (1), could you please paste the output of `:ls!`? (If you don't see `b.go` in tab 2 anymore, but still in tab 1, it means that `b.go` wasn't never really deleted in the first place.)

**Comment by mhinz** [comment]
Just so we're on the same page (pun intended), I added a minimal test to the repo. Try `vim -u test/test_2tab_1win_2buf.vim` from the repo and reproduce it there.

`:Sayonara` is mapped to `gs` and `:Sayonara!` to `gS`.

**Comment by fatih** [comment]
One tab two files are open:

![image](https://cloud.githubusercontent.com/assets/438920/7585142/7f62cf00-f8ab-11e4-93e0-8d8a310b354e.png)

After that I open another tab and the same two files:

![image](https://cloud.githubusercontent.com/assets/438920/7585169/958bf018-f8ab-11e4-95d2-e92b21e3025a.png)

Now when I do `:Sayonara` on the second tabs, second file, the second file in the first tab get disappeared: 

First tab:

![image](https://cloud.githubusercontent.com/assets/438920/7585263/e1e2ea20-f8ab-11e4-8197-d906ad4c4b7c.png)

Second tab:

![image](https://cloud.githubusercontent.com/assets/438920/7585257/d4f7b75a-f8ab-11e4-8b61-2b6e5ac0b51d.png)

## 

Now in my ideal world, what I would like to see is, `:Sayonara` should close only the window, not delete the buffer at all, because I have another window open with the same buffer in the first tab. But that one get's closed too. So maybe `:Sayonara` is not intended for this use case :) I thought it would, but if it's not than I'll move by not using it at all, as it's not suited for my use case.

**Comment by mhinz** [comment]
Hmmmm.

I guess I could implement a "reference counting" approach and make `:Sayonara` delete the current buffer unless the same buffer is shown in another window. In that case just `:close` the window.

Actually this sounds more useful than the current approach and still stays true to the original goal of buffer deletion.

**Comment by fatih** [comment]
Yeah, because I have already it somewhere else, it shouldn't be deleted. However if I have only one tab, and it's the only one, go ahead and delete it. Sometimes I have many tabs. One for actual coding, one for debugging, one for finding something. But it happens that the same file could be open in the coding tab and debugging tab. Once I'm finished debugging, I'll close all windows in that tab and go back working on my coding tab. Tab's are intended for this, it's a logical view of a set of windows aimed for a particular task.

**Comment by fatih** [comment]
There is also this plugin btw: https://github.com/moll/vim-bbye Maybe you are not aware of it.

**Comment by mhinz** [comment]
Yup, I know it, but all these plugins (bclose, bbye, bufkill) don't handle associated location lists, tabpages etc.

Just one last question before I'll go implement a first version: What if the same file is shown in two windows in the same tabpage? Same as before? Simply closing the the current window leaving the other window intact?

**Comment by fatih** [comment]
Exactly! This also happens quite a lot of to me (my own script for this was not good enough and couldn't handle it sometimes). There are files which are very large (say more than +800 lines). Sometimes you open a function which is located on top of the file, and then you split it with `ctrl+w ctrl+v` and go to the bottom and see each function next to next. Once I'm done I close the second view and go back to my first view (I'm still in the same tab).

**Comment by mhinz** [comment]
Splendid. Thanks for the feedback so far!

Now I'll go back to my cave and start implementing..

**Comment by mhinz** [comment]
Please try `git pull && git checkout experimental`.

It should work now as you'd expect:

`:Sayonara` closes the current window and deletes the buffer unless it's displayed in another window. If there's only one window, the tabpage gets closed. If there's only one tabpage, Vim quits.

`:Sayonara!` preserves the current window and deletes the buffer unless it's displayed in another window. If there's no other listed buffer to switch to, an empty scratch buffer is created.

I can find only one minor issue that happens because of the new design:
- `$ vim file`
- `<c-w>v` opens a new window
- `:Sayonara!` creates a scratch buffer since there's no other listed buffer (but doesn't delete the file)
- another `:Sayonara!` switches back to the file, since it's the only listed buffer

**Comment by fatih** [comment]
Works perfect! Thanks @mhinz. I've also mapped it to my close mapping:

``` viml
nnoremap <silent> <leader>q :Sayonara<CR>
```

And will try to use it extensively from now. This means If I see any errors or edge cases I'll let you know :)

**Comment by fatih** [comment]
Btw, it seems it broke this feature form your Readme.md:

```
If there is only a single window in the current tabpage, one of two things can happen:

there other listed buffers: switch to the previous buffer

there are no other listed buffers: either the current tabpage is closed or, if this is the only tabpage, Vim will quit
```

I have one tab, one window and `:ls` shows two buffers. Now when invoke `:Sayonara`, Vim quits. Is this ok? Or should it close that buffer and open the other buffer?

**Comment by mhinz** [comment]
> I have one tab, one window and :ls shows two buffers. Now when invoke :Sayonara, Vim quits. Is this ok? Or should it close that buffer and open the other buffer?

Okay, that _shouldn't_ happen, I'm looking into it.

**Comment by mhinz** [comment]
I updated the documentaion to reflect the current codebase and merged it into `master`.

Thanks for all the feedback, @fatih
